FROM node:18-alpine3.16
# Base Image node v18-alpine 3.16 사용

WORKDIR /app
# 컨테이너 내 work directory 설정

COPY ReqSys/package*.json .
# 현재 프로젝트의 package로 시작되는 모든 json 파일을 컨테이너 WORKDIR에 복사 

RUN npm install
# 이미지 생성 시 필요한 모듈 설치 

COPY ReqSys/ .
# 컨테이너 WORKDIR에 현재 프로젝트 내용 모두 복사

EXPOSE 3000
# 컨테이너 포트 지정 3000

CMD ["npm","run","start"]
# docker가 실행되면서 npm run start 실행 