FROM node:18-alpine3.16
# Base Image node v18-alpine 3.16 사용

WORKDIR /app
# 컨테이너 내 work directory 설정

COPY package*.json ./
# 현재 프로젝트의 package로 시작되는 모든 json 파일을 컨테이너 WORKDIR에 복사 

RUN npm install
# 이미지 생성 시 필요한 모듈 설치 

COPY . .
EXPOSE 3000
CMD [ "node", "app.js" ]
